# Generated by Django 5.0.6 on 2024-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_board_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('PROJ', 'Conduite de Projet'), ('KAN', 'Modèle Kanban'), ('TEAM', "Tableau de Bord d'équipe"), ('AGILE', 'Tableau Agile'), ('BUG', 'Traçage des anomalies')], default='PROJ', max_length=5, verbose_name='Type'),
        ),
    ]
