# Generated by Django 5.0.6 on 2024-05-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_card_options_board_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
