# Generated by Django 5.0.6 on 2024-05-20 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_board_date_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date de creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AddField(
            model_name='card',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
    ]
